[build]
builder = "RAILPACK"

[deploy]
startCommand = "./out -web -addr :8080 -data-folder /tmp/gmapsdata -c 8"
healthcheckPath = "/api/v1/jobs"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
